### ISSUE TITLE
19. As a user, I want to be able to delete a list

### ISSUE THREAD

**Issue by DevinaG007** [the-collab-lab/tcl-68-smart-shopping-list#40]
- [ ] Add a button element to the `Manage List` page that upon click, deletes the selected list
- [ ] When the user clicks the delete button, a confirmation pop up will ask the user to confirm if they want to delete the list
- [ ] The list is successfully deleted from the users' lists, and the user is navigated back to the `Home` page

**Comment by sdmisra** [comment]
Closed with https://github.com/the-collab-lab/tcl-68-smart-shopping-list/pull/47
