### ISSUE TITLE
28. List Styling

### ISSUE THREAD

**Issue by DevinaG007** [the-collab-lab/tcl-68-smart-shopping-list#58]
The following elements should be styled on our `List` page according to our prototype:
- [x]  `Header`: List name
- [x]  `Label`: Search for an item (rename to Filter?)
- [x] `Input Search Box`: Search for an item by name
- [x] `Button`: Reset
- [x] `Label`: Add new item
- [x] `Input Text Box`: Item Name
- [x] `Input Select Dropdown`: Next Purchase Date
- [x] `Button`: Add item
- [x] `List Items`: Items in the user's list
> - [x] Checkbox
> - [x] Icon
> - [x] Item Name
> - [x] Purchase Urgency
> - [x] `Button`: Delete

**Comment by andiedoescode** [comment]
Other styling needs:

- [x] `Button`: Select a list
- [x] `Header`: List is currently empty
- [x] `Header`: You haven't selected a list
